### ISSUE TITLE
Add usage example to README

### ISSUE THREAD

**Issue by donpdonp** [Sannis/node-ubjson#29]
The README could use an example. I'm having trouble with getting a hello-world going in node-ubjson. From reading the code I found packToBufferSync, but its buffer parameter requires a size during initialization. How am I to know the buffer size before the binary data (a string in this case) is ubjson-ified?

```javascript
var ubj = require('ubjson')

var buffer = new Buffer() 
ubj.packToBufferSync("binary data", buffer)
```
Error: First argument needs to be a number (in buffer.js)
Thanks!

**Comment by Sannis** [comment]
You should use pre-allocated buffer with synchronous methods. Otherwise you can use streaming interface.
